### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by seksitha** [albhm/macRX#3]
Hi I don't understand the readme file instruction. Can anyone or developer help me please. 
I download the file and the source code but there is no file macPPM file in the main directory and I try to run Makefile it just give a bunch of error in terminal. 

Any help please?

**Comment by albhm** [comment]
Hi,

the should be a binary is in macPPM.zip found under the ‘releases’ tab.

**Comment by seksitha** [comment]
Thank, now it initializing with no error. but My simulator doesn't seem to pick up the joystick. I use FPVfreerider drone software.  is it becuase of the software sim? 
And I use mac pro 10.11. I saw in your instruction need to be rebuild for 10.11 but I don't know how.
